version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_server
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./src/databases/qdrant_store:/qdrant/storage
    restart: unless-stopped
    environment:
      - QDRANT__STORAGE__BACKEND=local
      - QDRANT__STORAGE__PATH=/qdrant/storage
      - QDRANT__REST_PORT="6333"
      - QDRANT__GRPC_PORT="6334"
      - QDRANT__LOG_LEVEL=info
      - QDRANT__PERSISTENCE__BACKUP__ENABLED=true
      - QDRANT__PERSISTENCE__BACKUP__PATH=/qdrant/storage/backup
      - QDRANT__PERSISTENCE__BACKUP__INTERVAL="3600"